### ISSUE TITLE
Options to start maximised or minimised. 

### ISSUE THREAD

**Issue by SirWumpus** [BarRaider/streamdeck-advancedlauncher#1]
Sometimes to you need to start an application maximised, especially if you need to use Super Macro MOUSEPOS to click targets that have no key shortcut or command.  By starting maximised you have better control over MOUSEPOS X,Y without window repositioning issues.

**Comment by BarRaider** [comment]
This is currently achievable in a multi-action along with the Windows Mover & Resizer plugin.
Start by adding the Windows Mover & Resizer first with a command to maximize/minimize the app and THEN an Advanced Launcher with limiting the number of running instances to 1.

The button will be usable for both maximizing/minimizing while the app is open and to launching it in that state when it's not running

**Comment by SirWumpus** [comment]
Thank you for the tip.  I'll try that.
