### ISSUE TITLE
Some icon lag when changing folder

### ISSUE THREAD

**Issue by arnwik** [BarRaider/streamdeck-advancedlauncher#2]
I like your plugin a lot, but when changing folder, it lags. I usually use the applications own icons, and when moving between folder your default icon is shown for up to 2 secs before the original icon is displayed.

**Comment by BarRaider** [comment]
There is a short plugin load time in which the plugin receives the startup information from the Stream Deck SDK + Renders the app image. I've checked the code and there currently isn't a way to optimize this further.
